name: Modular

on:
  push:
    branches:
      - modular

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            skip: []
            os: ubuntu-latest
            shell: "bash"
            ext: "sh"
          - name: macOS
            skip: ["lexical_cast"]
            os: macos-13
            shell: "bash"
            ext: "sh"
          - name: Windows
            skip: ["hof"]
            os: windows-2022
            shell: "cmd"
            ext: "bat"
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: ${{matrix.shell}}
        working-directory: ${{github.workspace}}/boostroot
    env:
      B2: ${{github.workspace}}/b2/b2
    steps:
      - name: "Checkout Boost"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout B2"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        working-directory: ${{github.workspace}}/b2
        run: ./bootstrap.${{matrix.ext}}
      - name: callable_traits
        if: ${{ !contains(matrix.skip, 'callable_traits') }}
        run: '"${B2}" libs/callable_traits//all'
      - name: compatibility
        if: ${{ !contains(matrix.skip, 'compatibility') }}
        run: '"${B2}" libs/compatibility//all'
      - name: hof
        if: ${{ !contains(matrix.skip, 'hof') }}
        run: '"${B2}" libs/hof//all'
      - name: lexical_cast
        if: ${{ !contains(matrix.skip, 'lexical_cast') }}
        run: '"${B2}" libs/lexical_cast//all'
      - name: preprocessor
        if: ${{ !contains(matrix.skip, 'preprocessor') }}
        run: '"${B2}" libs/preprocessor//all'
