# Copyright 20242023 René Ferdinand Rivera Morell
# Use, modification, and distribution are subject to the
# Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)

name: "Check Libraries Docs"

on:
  # Allow manual runs.
  workflow_dispatch:
  push:
    branches:
      - modular
    paths-ignore:
      - ".github/workflows/ci.yml"
      - ".github/workflows/modular-check-libs.yml"
      - ".github/workflows/modular-release.yml"

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        lib:
          - accumulators
          - algorithm
          - align
          - any
          - array
          - asio
          - assert
          - atomic
          - beast
          - bimap
          - bind
          - callable_traits
          - charconv
          - circular_buffer
          - cobalt
          - compat
          - compute
          - concept_check
          - config
          - container
          - container_hash
          - context
          - contract
          - conversion
          - convert
          - core
          - coroutine
          - coroutine2
          - crc
          - date_time
          - describe
          - detail
          - dll
          - endian
          - fiber
          - filesystem
          - foreach
          - function
          - function_types
          - functional
          - fusion
          - geometry
          - hana
          - heap
          - histogram
          - hof
          - icl
          - integer
          - interprocess
          - intrusive
          - io
          - iterator
          - json
          - lambda
          - lambda2
          - leaf
          - lexical_cast
          - local_function
          - locale
          - lockfree
          - log
          - logic
          - math
          - metaparse
          - move
          - mp11
          - mpi
          - multi_array
          - multiprecision
          - mysql
          - nowide
          - numeric/ublas
          - optional
          - parameter
          - parameter_python
          - pfr
          - phoenix
          - poly_collection
          - pool
          - predef
          - process
          - program_options
          - property_tree
          - proto
          - qvm
          - random
          - range
          - ratio
          - redis
          - regex
          - scope
          - scope_exit
          - signals2
          - smart_ptr
          - sort
          - spirit
          - stacktrace
          - static_assert
          - static_string
          - stl_interfaces
          - system
          - test
          - thread
          - throw_exception
          - tti
          - tuple
          - type_erasure
          - type_index
          - type_traits
          - typeof
          - units
          - unordered
          - url
          - utility
          - uuid
          - variant
          - variant2
          - vmd
          - winapi
          - xpressive
          - yap
          # Quickbook gets stuck in indefinite loop.
          # - chrono
          # Sphinx irreparably complain about something undefined.
          # - gil
          # - python
          # Nothing to build / pre-built..
          # - assign
          # - compatibility
          # - dynamic_bitset
          # - exception
          # - flyweight
          # - format
          # - graph
          # - graph_parallel
          # - headers
          # - iostreams
          # - mpl
          # - msm
          # - multi_index
          # - numeric/conversion
          # - numeric/interval
          # - numeric/odeint
          # - outcome
          # - polygon
          # - preprocessor
          # - property_map
          # - property_map_parallel
          # - ptr_container
          # - rational
          # - safe_numerics
          # - serialization
          # - statechart
          # - timer
          # - tokenizer
          # - wave
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash"
        working-directory: ${{github.workspace}}/boostroot
    steps:
      - name: "Setup"
        working-directory: ${{github.workspace}}
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get -o Acquire::Retries=3 update -y
          sudo apt-get -o Acquire::Retries=3 -y install \
            asciidoctor \
            docbook \
            docbook-xml \
            docbook-xsl \
            docutils-common \
            docutils-doc \
            doxygen \
            fop \
            g++-13 \
            ghostscript \
            libsaxonhe-java \
            liburing-dev \
            texlive \
            texlive-latex-extra \
            xsltproc
          pip3 install --user --upgrade Sphinx
          pip3 install --user --upgrade sphinx-boost
          pip3 install --user --upgrade myst-parser
      - name: "Checkout Boost Root"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout B2"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        working-directory: ${{github.workspace}}/b2
        run: ./bootstrap.sh
      - name: Config
        run: |
          echo "using asciidoctor ;" >> $HOME/user-config.jam
          echo "using auto-index ;" >> $HOME/user-config.jam
          echo "using boostbook ;" >> $HOME/user-config.jam
          echo "using quickbook ;" >> $HOME/user-config.jam
          echo "using xsltproc ;" >> $HOME/user-config.jam
          echo "using doxygen ;" >> $HOME/user-config.jam
          echo "using fop ;" >> $HOME/user-config.jam
          echo "using saxonhe ;" >> $HOME/user-config.jam
          echo "using docutils : /usr/share/docutils ;" >> $HOME/user-config.jam
      - name: Check
        run: '"${{github.workspace}}/b2/b2" --debug-configuration "--build-dir=${{github.workspace}}/bin" libs/${{matrix.lib}}/doc//boostdoc libs/${{matrix.lib}}/doc//boostrelease'
