name: Modular

on:
  push:
    branches:
      - modular

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        run: |
          cd "${{github.workspace}}/b2"
          ./bootstrap.sh
      - { name: callable_traits, run: 'set -e && cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/callable_traits//all' }
      - { name: compatibility, run: 'set -e && cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/compatibility//all' }
      - { name: hof, run: 'set -e && cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/hof//all' }
      - { name: lexical_cast, run: 'set -e && cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/lexical_cast//all' }
      - { name: preprocessor, run: 'set -e && cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/preprocessor//all' }

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
    runs-on: ${{matrix.os}}
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        shell: cmd
        run: |
          cd "${{github.workspace}}/b2"
          ./bootstrap.bat
      - { name: callable_traits, shell: cmd, run: 'cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/callable_traits//all' }
      - { name: compatibility, shell: cmd, run: 'cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/compatibility//all' }
      # - { name: hof, shell: cmd, run: 'cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/hof//all' }
      - { name: lexical_cast, shell: cmd, run: 'cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/lexical_cast//all' }
      - { name: preprocessor, shell: cmd, run: 'cd "${{github.workspace}}/boostroot" && "${{github.workspace}}/b2/b2" libs/preprocessor//all' }
