name: Modular Release

on:
  workflow_dispatch:
  push:
    branches:
      - modular

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}/boostroot
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Setup"
        run: |
          sudo apt-get -o Acquire::Retries=3 update
          sudo apt-get -o Acquire::Retries=3 -y install \
            p7zip-full \
            curl \
            docutils-common \
            docutils-doc \
            docbook \
            docbook-xml \
            docbook-xsl \
            dvipsk-ja \
            xsltproc \
            graphviz \
            texlive \
            ghostscript \
            unzip \
            ruby \
            python-docutils \
            libsaxonhe-java \
            cmake \
            bison \
            flex \
            texlive-latex-extra \
            default-jre-headless \
            doxygen
          pip3 install future
      - name: "Release"
        run: |
          wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_common.py" -P ${{github.workspace}}
          wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_release.py" -P ${{github.workspace}}
          python3 ${{github.workspace}}/ci_boost_release.py checkout_post
          EOL=LF python3 ${{github.workspace}}/ci_boost_release.py test_pre
          EOL=LF python3 ${{github.workspace}}/ci_boost_release.py test_override
